{ username, ... }:

{
  # Set as trusted users for using mirrors
  nix.settings.trusted-users = [ username ];

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$y$j9T$taWQyCw5HrrBRkx8uNHO50$1DIFg45L4E3A9MhjeI4FenL2xNPHDkT5BBH/NtUwlp0";
    home = "/home/${username}";
    isNormalUser = true;
    extraGroups = [
      username
      "users"
      "wheel"
      "docker"
      "adbusers"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkjhbJRkAagX4N/lMyL/sRvg2qzZHntu4ZHXO+NCI1BetA1kykVSjA0MS5E0jJ5+ACihCeqmivzNiOFoZvQ1quBNKU4XF3b7MnkfW93qH1ET30klzO7kV6+5ycH/hLHENsZB4YEghSUrictxkDADlvlhKORFFoLK/aUVwfHgONaRius9beKevsDmrlnIVBUiuaj//WbyHVWBeJBdRVFaLChvD8qq/bjVEij5vE41u9lZhz1MU2IHEHSp60kXLUILwlR0rr+F+1OXtF9oqOwzNdBs181oJal9fA/G11CPbnCeqjq7I+shA03XAooXuTm9Ni0CPb+FZSzcUeDzTrjGoj yang@NII"
    ];
  };

  # Turn off password prompt when using sudo.
  security.sudo.extraRules = [
    {
      users = [username];
      commands = [
        {
          command = "ALL";
          options = ["NOPASSWD"];
        }
      ];
    }
  ];
}